---
title: ""
author: "Jordan Wheeler"
description: "Jordan Wheeler's Running"
---

<meta name="author" content="Jordan Wheeler">
<meta name="description" content="Jordan Wheeler's Running">

<style>
  .flat-table {
    display: block;
    font-family: sans-serif;
    -webkit-font-smoothing: antialiased;
    font-size: 115%;
    overflow: auto;
    width: auto;
  }
  thead {
    background-color: black;
    color: white;
    font-weight: normal;
    padding: 20px 30px;
    text-align: center;
  }
  tbody {
    background-color: white;
    color: rgb(102, 102, 102);
    padding: 20px 30px;
  }
  .center {
    margin-left: auto;
    margin-right: auto;
    display: block
}
</style>

<h3><a href="https://www.strava.com/athletes/30817358" target="_blank">Strava Running Profile</a></h3>
<h3><a href="https://connect.garmin.com/modern/profile/41e46247-dcbc-44da-8247-707f7ca17b87" target="_blank">Garmin Connect Profile</a></h3>
<h3><a href="https://www.tfrrs.org/athletes/5486844.html" target="_blank">TFRRS Profile</a></h3>

<hr style="border-color: #666666;">

<h3>Accolades:</h3>
<ul>
<li><h5>NCAA Outdoor Track and Field National Championship Qualifier - 10,000 Meters</h5></li>
<li><h5>Second Team All American - Outdoor Track and Field, NCAA Division III</h5></li>
<li><h5>NCAA Cross Country National Championship Qualifier</h5></li>
<li><h5>Nebraska Wesleyan University's First-Year Outdoor 10,000 Meters record holder</h5></li>
<li><h5><a href="RunningTables/GPACResults2015.pdf" target="_blank">GPAC Conference Cross Country Individual Champion</a></h5></li>
<li><h5><a href="http://www.gpacsports.com/article/3470.php#.Wya1Mi8-KL4" target="_blank">GPAC Cross Country Runner of the Year</a></h5></li>
<li><h5>GPAC Conference Indoor Track and Field Champion - 5,0000 Meters</h5></li>
<li><h5>Academic All-Conference Team - Cross Country</h5></li>
<li><h5>Academic All-Conference Team - Track and Field</h5></li>
<li><h5>USTFCCCA All Academic Scholar Athlete</h5></li>
<li><h5><a href="RunningTables/GrinnellMeetRecords.pdf" target="_blank">Grinnell College: Darren Young Classic Invite Record Holder in 5,000 Meters</a></h5></li>
</ul>
<hr style="border-color: #666666;">

<h3>Personal Bests:</h3>
<table class="table table-bordered table-hover table-condensed">
<thead><tr>
<td>Event</td>
<td>Time</td>
<td>Meet</td>
<td>Date</td>
</tr></thead>
<tbody>
<tr>
<td>1500 Meters (Outdoors)</td>
<td>4:12.40</td>
<td>NWU v. Doane Dual</td>
<td>April 15, 2016</td>
</tr>
<tr>
<td>Mile (Indoors)</td>
<td>4:28.99</td>
<td>Missouri Collegiate Challenge</td>
<td>February 20, 2015</td>
</tr>
<tr>
<td>3000 Meters (Indoors)</td>
<td>8:34.04</td>
<td>Frank Sevigne Husker Invitational</td>
<td>February 3, 2018</td>
</tr>
<tr>
<td>5000 Meters (Indoors)</td>
<td>14:45.95</td>
<td>Frank Sevigne Husker Invitational</td>
<td>February 5, 2016</td>
</tr>
<tr>
<td>5000 Meters (Outdoors)</td>
<td>15:09.88</td>
<td>Concordia Invite</td>
<td>April 8, 2017</td>
</tr>
<tr>
<td>8000 Meters (Cross Country)</td>
<td>25:08.20</td>
<td>Jim Drews/Tori Neubauer Invitational</td>
<td>October 17, 2015</td>
</tr>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>30:23.91</td>
<td>Drake Relays</td>
<td>April 26, 2017 </td>
</tr>
</tbody></table>

<hr style="border-color: #666666;">

<h3>Regional and National Meet Performances:</h3>
<table class="table table-bordered table-hover table-condensed">
<thead><tr>
<td>Event</td>
<td>Meet</td>
<td>Time</td>
<td>Place</td>
</tr></thead>
<tbody>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>2014 NCAA Division II Midwest Region Cross Country Championships</td>
<td>32:51.40</td>
<td>61</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2015 NCAA Division III Central Region Cross Country Championships</td>
<td>26:03.40</td>
<td>17</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2016 NCAA Division III Central Region Cross Country Championships</td>
<td>25:59.50</td>
<td>17</td>
</tr>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>2017 NCAA Division III Outdoor Track &amp; Field Championships</td>
<td>31:26.09</td>
<td>16</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2017 NCAA Division III Central Region Cross Country Championships</td>
<td>25:16.90</td>
<td>7</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2017 NCAA Division III Cross Country Championships</td>
<td>25:32.20</td>
<td>105</td>
</tr>
</tbody></table>

<hr style="border-color: #666666;">

<h3>Conference Performances:</h3>
<table class="table table-bordered table-hover table-condensed">
<thead><tr>
<td>Event</td>
<td>Year</td>
<td>Time</td>
<td>Place</td>
</tr></thead>
<tbody>
<tr>
<td>8000 Meters (XC)</td>
<td>2014</td>
<td>25:59.20</td>
<td>32</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2015</td>
<td>25:32.20</td>
<td>1</td>
</tr>
<tr>
<td>3000 Meters (Indoors)</td>
<td>2016</td>
<td>8:39.34</td>
<td>2</td>
</tr>
<tr>
<td>5000 Meters (Indoors)</td>
<td>2016</td>
<td>15:12.17</td>
<td>1</td>
</tr>
<tr>
<td>5000 Meters (Outdoors)</td>
<td>2016</td>
<td>15:32.03</td>
<td>3</td>
</tr>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>2016</td>
<td>32:34.17</td>
<td>2</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2016</td>
<td>25:32.10</td>
<td>9</td>
</tr>
<tr>
<td>3000 Meters (Indoors)</td>
<td>2017</td>
<td>8:47.41</td>
<td>8</td>
</tr>
<tr>
<td>5000 Meters (Indoors)</td>
<td>2017</td>
<td>15:05.09</td>
<td>4</td>
</tr>
<tr>
<td>5000 Meters (Outdoors)</td>
<td>2017</td>
<td>15:24.49</td>
<td>4</td>
</tr>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>2017</td>
<td>31:51.10</td>
<td>4</td>
</tr>
<tr>
<td>8000 Meters (XC)</td>
<td>2017</td>
<td>25:46.00</td>
<td>9</td>
</tr>
<tr>
<td>3000 Meters (Indoors)</td>
<td>2018</td>
<td>8:57.59</td>
<td>8</td>
</tr>
<tr>
<td>5000 Meters (Indoors)</td>
<td>2018</td>
<td>15:07.77</td>
<td>4</td>
</tr>
<tr>
<td>5000 Meters (Outdoors)</td>
<td>2018</td>
<td>15:33.22</td>
<td>15</td>
</tr>
<tr>
<td>10000 Meters (Outdoors)</td>
<td>2018</td>
<td>32:26.08</td>
<td>9</td>
</tr>
</tbody></table>

<hr style="border-color: #666666;">

<h3>2015 GPAC Conference Championship:</h3>

<!-- 16:9 aspect ratio -->
<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/d1Jc6kFiC58"></iframe>
</div>

<hr style="border-color: #666666;">

